version: "3"
services:
  stories:
    build:
      context: .
    restart: always
    environment:
      CONTENT_LOCATION: "/content"
    volumes:
      - ../publisher-content:/content
    ports:
      - "8082:80"
